spring:
  profiles: 
    active: local

---

spring:
  profiles: local
  application:
    name: emp-api
    
server:
  port: 5678

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka
  instance:
    preferIpAddress: true

sidecar:
  hostname: localhost
  port: 5001
  health-uri: http://${sidecar.hostname}:${sidecar.port}/health

---

spring:
  profiles: prod
  application:
    name: emp-api
      
server:
  port: 5678

eureka:
  client:
    serviceUrl:
      defaultZone: http://218.151.225.142:8761/eureka
  instance:
    preferIpAddress: true

sidecar:
  hostname: localhost
  port: 5001
  health-uri: http://${sidecar.hostname}:${sidecar.port}/health  